title:              Clean Blog
email:              knc0827@naver.com
description:        Story written by Wonchan Kim
author:             Wonchan Kim
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://kim-wonchan.github.io/"

# Social Profiles
twitter_username:   
github_username:    kim-wonchan
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
